language: bash
sudo: true

script:
  - echo "Haaaallllllllllllllllllllooooooooooooooooooooooooooooooooooo"

language: node_js
node_js:
  - "0.10"
notifications:
  email: false
#before_script:
  #- npm install
  #- npm install source-map