language: node_js
sudo: true
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "openwhisk/joke/node_modules"
    - "openwhisk/meal/node_modules"
    - "openwhisk/router/node_modules"
    - "openwhisk/timetables/node_modules"
    - "openwhisk/weather/node_modules"
notifications:
  email: false
#before_script:
  #- npm install
  #- npm install source-map
script:
    - chmod +x ./travis_test.sh
    - chmod +x ./deploy_test.sh
    - chmod +x ./deploy.sh
    - echo "Bundle selected Javascript files"
    - npm run-script browserify
    - echo "Uglify Bundle.js"
    - grunt uglify
    - sed 's/$CONVERSATION_USERNAME/'"\'${CONVERSATION_USERNAME}\'"'/g' -i openwhisk/router/lib/conversation.js
    - sed 's/$CONVERSATION_PASSWORD/'"\'${CONVERSATION_PASSWORD}\'"'/g' -i openwhisk/router/lib/conversation.js
<<<<<<< HEAD
    # url with username and password is in Weather action (still not working)
=======
    - sed 's/$CONVERSATION_WORKSPACE_ID/'"\'${CONVERSATION_WORKSPACE_ID}\'"'/g' -i openwhisk/router/lib/conversation.js
>>>>>>> ba769fa618beaaecf1839b371c6126cec755bb1b
    - sed 's%$WEATHER_COMPANY_URL%'"\'${WEATHER_COMPANY_URL}\'"'%g' -i openwhisk/weather/lib/Weather.js
    - ./travis_test.sh
    - export PATH=$PATH:`pwd`  # make openwhisk cli available here
    - echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Undeploying wsk actions for testing~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    - ./deploy_test.sh --uninstall
    - ./deploy.sh --uninstall
    - ./deploy.sh --install
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master