language: node_js
sudo: true
node_js:
  - "0.10"
notifications:
  email: false
provider: script
script:
    - chmod +x ./travis_test.sh
    - chmod +x ./deploy_test.sh
    - ./travis_test.sh
    - npm test
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master

#before_script:
  #- npm install
  #- npm install source-map