language: node_js
sudo: true
node_js:
  - "0.10"
notifications:
  email: false
provider: script
script:
    - cd openwhisk
    - ./test-travis.sh
    - cd ..
    - npm test

#before_script:
  #- npm install
  #- npm install source-map