language: node_js
node_js:
  - "0.10"
notifications:
  email: false
script:
    - cd openwhisk
    - sudo ./test-travis.sh
    - cd ..
    - npm test

#before_script:
  #- npm install
  #- npm install source-map