language: node_js
sudo: true
node_js:
  - "0.10"
notifications:
  email: false
provider: script
script:
    - cd openwhisk
    - chmod +x ./test_travis.sh
    - chmod +x ./test_deploy.sh
    - ./test_travis.sh
    - cd ..
    - npm test

#before_script:
  #- npm install
  #- npm install source-map