language: node_js
sudo: true
node_js:
  - "0.10"
cache:
  directories:
    - "node_modules"
    - "openwhisk/joke/node_modules"
    - "openwhisk/meal/node_modules"
    - "openwhisk/router/node_modules"
    - "openwhisk/timetables/node_modules"
notifications:
  email: false
provider: script
script:
    - chmod +x ./travis_test.sh
    - chmod +x ./deploy_test.sh
    - chmod +x ./deploy.sh
    - echo "Bundle selected Javascript files"
    - npm run-script browserify
    - echo "Uglify Bundle.js"
    - grunt uglify
    - ./travis_test.sh
    - ./deploy.sh --uninstall
    - ./deploy.sh --install
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master

#before_script:
  #- npm install
  #- npm install source-map